# Generated by Django 5.2.1 on 2025-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='link',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='title',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='position',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], max_length=50),
        ),
    ]
